### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by lehnerpat** [JohnWeisz/BoundMethods#2]
Hi! Thanks for writing and publishing this decorator, it's a nice way to make method binding easily usable.

Unfortunately, your solution doesn't currently state under which license you've published it.
That is generally fine (and up to you), but makes it difficult and/or undesirable for other people to just use your code as-is. You can find [some details on what terms imply implicitly if you don't choose a software license on choosealicense.com](https://choosealicense.com/no-license).

I stumbled over your solution because i'm planning to write a short blog post about "the bind problem," and I'd like to refer and link to this repository.
I'd feel much better about that if it were open source with a permissive license :)

You can find a bunch of concise information here: https://choosealicense.com/

Personally, I'd recommend a [BSD-style](https://choosealicense.com/licenses/bsd-3-clause/) or an [MIT](https://choosealicense.com/licenses/mit/) license.

Thanks again!

**Comment by JohnWeisz** [comment]
To be honest, I forgot I even had this repository, so let's just go with MIT here. I'll add the license straight away.

**Comment by lehnerpat** [comment]
Hah, that definitely has happened to me before :D

Thanks a lot for the quick reply!
